#!/bin/bash

set -o errexit
set -o nounset

ASDB_REINIT={{ASDB_REINIT}}
PSQL_HOST={{PSQL_HOST}}
PSQL_PORT={{PSQL_PORT}}
PSQL_USER={{PSQL_USER}}
PSQL_DB={{PSQL_DB}}
PSQL_SCHEMA={{PSQL_SCHEMA}}

PSQL="psql -h $PSQL_HOST -p $PSQL_PORT -U $PSQL_USER"
PSQL_AS="$PSQL $PSQL_DB"
$PSQL_AS -c "DROP DATABASE  IF EXISTS ${PSQL_DB};"

